// ~/300_asciidoc_writers_guide/000_includes/documents/200_building_documents/
// Chapter document: 200_building_documents.asciidoc
// -----------------------------------------------------------------------------

== Building documents

Coming back to chapter link:{uri-chapter-non-disturbing}[Non disturbing Techniques],
the *Act of Writing* includes a lot of very formal, more ore less mind-less
activities. Sounds quite boring but it's *not*. Many people have fun things to
do like *ironing*. You'll have nice results, and your can wander your thoughts,
even watching TV. That is really great, the beginning of what I call the *Flow*.

The *Flow* is important. As much as possible prevent situations you get *stuck*.
For sure, you will experience getting stick on searching a good explanation,
good words - searching for a good idea. You will need what's called
*inspiration* -- but cannot force them. For that reason calm you down: a lot
of formal activities are waiting that needs to be done.

Enough space for the *Flow*.

The name of this chapter is *Building documents* -- that's not for chance.
The name *Building documents* should imply what is means: build a document, no
writing. No brick layer goes for thinking what a brick is, how to create them.
There are already bricks available. Otherwise it wouldn't possible to build
that house.

Think along that picture: building a house is the base, but to get a house
furnished a completely different thing. Who has ever build a house will
remenber very different phases of that *project*. If the construction is
finished, a another quite exhausting job is waiting for you. Make that house
a living space for you and your family. That situation has quite a lot of
similarities to what I called *editing*.

Like the construction of a house, building documents needs many different
things to do. Different craftspeople were morking on that house; from the
roof to the cellar. Quite the same to building documents. But: you are the
builder, no experinced craftspeople will take care.

What's needed to build the base of a document, no visionary is needed. Houses
are different but using the same components. For that reason I created a
raw base for that: the document skeleton.

A starter site created by the _J1 Template_ Ruby gem includes the skeleton.
Located in root folder of such a site. You'll find the skeleton as zip file:
*asciidoc_document_skeleton.zip* under the directoty *_templates*.

Now, it's time to make your hands dirty!
Go for *The Document Skeleton*.
//Go for link:{uri-chapter-document-skeleton}[The Document Skeleton]
