The following characterizes a static web generated by a *Site Generator*:

* Static sites can be written almost exclusively in HTML and serve a fixed
  set of data that renders the same for every site visitor. Static sites use
  server-side rendering to serve pre-built HTML, CSS, and JavaScript files to
  a web browser.

* A static site serves the content straight to the user as it is stored on
  the server-side. In opposition to CMS systems which use a database to load
  dynamic content, a static site will display the same content to every user
  as it will directly load the HTML files on the server.

* Using a static site generator like *Jekyll*, the engine separates the content
  from the Template. By using a static site generator, you will only need to
  make the modification once, and the generator will apply it to all your
  pages.

The template system *J1* use _Jekyll_ under the hood and provides a lot of
high-level functions to control the web creation process:

* J1 is highly *customizable*. Based on a pure configuration, a website can
  be created. The template system creates static web pages using Jekyll as
  the base HTML code generator.

* For J1, a rich set of modules are already included. The modules support
  usual use cases of a website like a flexible navigation system, a local
  search, lightboxes to present pictures and videos, little helpers for
  scrolling, or to automatically create TOCs (table of contents) for a page.

Let's start by creating a static web and *verify* if and what that means
for your *First awesome Web*.


== A First awesome Web

Remember:

[subs=+macros]
----
  A GEM can contain command-line interfaces (CLI, commands) to access
  higher-level functionality. Jekyll and J1 use that to provide the CLI
  commands jekyll and j1.
----

The J1 Template GEM contains such an command-line interface: *j1*. The command
is used to create (generate) a web *project*. Generate such a project is the
very first step to manage a *new* website.

First, a project *folder* is needed to place the (project) files. A project
can be gereated elsewhere, but I recommend to create a *Web* folder first
to place (all) generated websites at a central place.

.Base folder for all webs generated
[source, msshell]
----
md C:\J1Webs
----
