After many technical topics in the past chapters, let's now discuss writing
content. You will learn how to create articles and integrate them with the
J1 navigation system.

I'll cover some fundamental aspects of using a website generator in the
following two sections. The focus is on how Jekyll documents are structured
and how the engine processes them. Another important aspect will be the markup
language Asciidoc and what role markups play for your content.

== The template GEM

The hidden folders ...

== Page architecture

Bubble up the data

----
source page | page layout | default layout | html page
----

=== Layouts

==== Default layout

==== Page layout

=== Front Matter

==== Front Matter defaults

=== Assets

=== Resources



== Creating simple documents

=== Creating pages

== Authoring with Asciidoc


== Creating complex documents

=== Using includes

=== Using HTML blocks



.Processing chain (simplified)
lightbox::kickstart-wiad--processing-chain-1[ 800, {data-kickstart-wiad--processing-chain-1} ]


.Processing chain (Liquid + Asciidoc includes)
lightbox::kickstart-wiad--processing-chain-2[ 800, {data-kickstart-wiad--processing-chain-2} ]
