{% comment %}
 # -----------------------------------------------------------------------------
 #  ~/_includes/themes/j1/procedures/posts/create_series_header.proc
 #  Liquid PROCEDURE to create a series header for post series
 #
 #  http://jekyll.one
 #
 #  Copyright (C) 2020 Juergen Adams
 #
 #  J1 Template is licensed under the MIT License.
 #  See: https://github.com/jekyll-one-org/J1 Template/blob/master/LICENSE
 #
 # -----------------------------------------------------------------------------
 #   Posts procedure. Generates ...
 #
 #    Usage:
 #
 #      1)  assign the 'page', 'post' and 'readmore' variables
 #      2)  include the create_series_header.proc procedure
 #
 #    Example:
 #
 #      {% capture create_series_header %}themes/{{site.template.name}}/procedures/posts/create_series_header.proc{% endcapture %}
 #      {% assign my_navigation_data = nav_data_array %}
 #
 #      {% include {{create_series_header}} page=page post=post %}
 #
 # -----------------------------------------------------------------------------
 # Test data:
 #  liquid_var:  {{liquid_var | debug}}
 #
 # -----------------------------------------------------------------------------
{% endcomment %}

{% comment %} Liquid procedures
-------------------------------------------------------------------------------- {% endcomment %}

{% comment %} Variables
-------------------------------------------------------------------------------- {% endcomment %}
{% assign readmore = false %}
{% assign page     = include.page %}
{% assign post     = include.post %}
{% assign readmore = include.readmore %}


{% comment %} Main
-------------------------------------------------------------------------------- {% endcomment %}
{% assign count = '0' %}
{% assign idx = '0' %}
{% assign list = '' %}

{% capture open %}
<div id="post_series">
 <div class="series-navigator ml-3"> 
   <div class="content series-navigation">

     <div class="row">
       <div class="col-xs-12 col-md-12 col-lg-12 mb-4">
         <h5 id="blog_series_list" class="notoc mt-2 mr-2 mb-4">This article is <strong>part <<idx>> </strong> in a <strong><<count>>-part</strong> series:</h5>
         <ul class="side-nav">
 {% endcapture %}
         {% for post in site.posts reversed %}
           {% if post.series == page.series %}
             {% assign count = count | plus: 1 %}
             {% if post.url == page.url %}
               {% assign idx = count %}
               {% assign excerpt = post.excerpt %}
               {% assign excerpt_title = post.tagline|capitalize %}
             {% endif %}
             {% capture list_tmp %}{{list}}{% if page.url == post.url %}<li class="current"><a data-proofer-ignore href="#">{{post.date|date: "%Y-%m-%d"}} · Part {{count}} · {{post.title}}</a>{% else %}<li><a data-proofer-ignore href="{{site.baseurl}}{{post.url}}">{{post.date|date: "%Y-%m-%d"}} · Part {{count}} · {{post.title}}</a>{% endif %}</li>{% endcapture %}
             {% assign list = list_tmp %}
           {% endif %}
         {% endfor %}
         {{open | replace: '<<count>>', count | replace: '<<idx>>', idx}}{{list}}
         </ul>
       </div>

       <div class="col-xs-12 col-md-12 col-lg-12 mt-2">
         <h5 class="notoc series-exerpt-title">{{excerpt_title}}</h5>
         <div class="series-exerpt mr-3">
           <div class="paragraph">
             <p>{{excerpt}}</p>
           </div>
           {% if readmore %}
           <div class="card-footer">
             <a href="#readmore" class="btn btn-info btn-raised pull-right smoothscroll"> <i class="mdi mdi-eye mdi-lg" style="color:#FFFFFF" %}=""></i> Read More </a>
           </div>
           {% endif %}

         </div>
       </div>
     </div>

   </div>
 </div>
</div>
