---
title:                                  Web in a Day
tagline:                                meet & greet
date:                                   2021-04-01 00:00:00 +100
description: >
                                        Web in a Day is the first in a series of tutorials to
                                        learn how to create modern websites using Jekyll. This
                                        Kickstarter focus on the basics of Jekyll and the
                                        J1 Template which all people needs to know for a successful
                                        way to a modern static website using Jekyll and J1 Template

categories:                             [ Knowledge, Tutorial ]
tags:                                   [ Jekyll, J1 ]

scrollbar:                              false
comments:                               true

permalink:                              /pages/public/learn/kickstarter/web_in_a_day/meet_and_greet/
regenerate:                             false

resources:                              [ lightbox ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/kickstarter/web_in_a_day/100_meet_and_greet/roman-kraft-1920x1280.jpg
          alt:                          Photo by Roman Kraft on Unsplash
          alignY:                       top
          badge:
            type:                       unsplash
            author:                     Roman Kraft
            href:                       https://unsplash.com/@romankraft
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set page (local) attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents
// -----------------------------------------------------------------------------
include::{documentdir}/100_meet_and_greet.asciidoc[]

== Questions

include::{includedir}/parts.asciidoc[tag=questions-chapter]

[role="big bold"]
mdi:head-question-outline[24px, md-grey-700 mb-5 mr-2]
link:{j1-kickstart-wiad--answer-1}[Question 1, {browser-window--new}]

[QUESTION]
====
What is the general difference between dynamic and static websites in terms
of using databases?
====

[role="big bold"]
mdi:head-question-outline[24px, md-grey-700 mb-5 mr-2]
link:{j1-kickstart-wiad--answer-2}[Question 2, {browser-window--new}]

[QUESTION]
====
Static websites are considered to be safe. Are there any reasons for this?
====

[role="big bold"]
mdi:head-question-outline[24px, md-grey-700 mb-5 mr-2]
link:{j1-kickstart-wiad--answer-3}[Question 3, {browser-window--new}]

[QUESTION]
====
Are there any reasons to use a site generator for static websites?
====


== Summarize!

include::{includedir}/parts.asciidoc[tag=summarize]

=== Recap

include::{includedir}/parts.asciidoc[tag=recap_100_meet_and_greet]

=== Whats Next

include::{includedir}/parts.asciidoc[tag=whats_next_100_meet_and_greet]

=== All Chapters

include::{includedir}/parts.asciidoc[tag=chapters]
include::{includedir}/parts.asciidoc[tag=chapters_100_meet_and_greet]

=== Further Reading

include::{includedir}/parts.asciidoc[tag=further_reading]
include::{includedir}/parts.asciidoc[tag=further_reading_100_meet_and_greet]

== Leave a comment
