---
title:                                  Web in a Day
tagline:                                getting prepared
date:                                   2021-04-02 00:00:00 +100
description: >
                                        Modern static website in a day

categories:                             [ Knowledge, Tutorial ]
tags:                                   [ Preparations ]

scrollbar:                              false
comments:                               true

permalink:                              /pages/public/learn/kickstarter/web_in_a_day/getting_prepared/
regenerate:                             false

resources:                              [ lightbox, clipboard, rouge ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/kickstarter/web_in_a_day/110_getting_prepared/jeshoots-1-1920x1280.jpg
          alt:                          Photo by JESHOOTS.COM on Unsplash
          alignY:                       top
          badge:
            type:                       unsplash
            author:                     JESHOOTS.COM
            href:                       https://unsplash.com/@jeshoots/portfolio
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set page (local) attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents
// -----------------------------------------------------------------------------
include::{documentdir}/110_getting_prepared.asciidoc[]

== Questions

include::{includedir}/parts.asciidoc[tag=questions-chapter]


[role="big bold"]
mdi:head-question-outline[24px, md-grey-700 mb-5 mr-2]
link:{j1-kickstart-wiad--answer-4}[Question 4, {browser-window--new}]

[QUESTION]
====
What user can install software on Windows?
====

[role="big bold"]
mdi:head-question-outline[24px, md-grey-700 mb-5 mr-2]
link:{j1-kickstart-wiad--answer-5}[Question 5, {browser-window--new}]

[QUESTION]
====
For _Ruby_, GEMs (libraries) can be installed *system-wide* or *userized*.
What are the differences?
====

[role="big bold"]
mdi:head-question-outline[24px, md-grey-700 mb-5 mr-2]
link:{j1-kickstart-wiad--answer-6}[Question 6, {browser-window--new}]

[QUESTION]
====
If _Ruby_ GEMs are installed *userized*, what is to be considered to make
userized GEMs fully accessible?
====

== Summarize!

include::{includedir}/parts.asciidoc[tag=summarize]

=== Recap

include::{includedir}/parts.asciidoc[tag=recap_110_getting_prepared]

=== Whats Next

include::{includedir}/parts.asciidoc[tag=whats_next_110_getting_prepared]

=== All Chapters

include::{includedir}/parts.asciidoc[tag=chapters]
include::{includedir}/parts.asciidoc[tag=chapters_110_getting_prepared]

=== Further Reading

include::{includedir}/parts.asciidoc[tag=further_reading]
include::{includedir}/parts.asciidoc[tag=further_reading_110_getting_prepared]

== Leave a comment
