---
title:                                  Web in a Day
tagline:                                first awesome web
date:                                   2021-04-08 00:00:00 +100
description: >
                                        Modern static website in a day

categories:                             [ Knowledge, Tutorial ]
tags:                                   [ Generating, Webs ]

scrollbar:                              false
comments:                               true

permalink:                              /pages/public/learn/kickstarter/web_in_a_day/a_first_awesome_web/
regenerate:                             false

resources:                              [ lightbox, clipboard, rouge ]
resource_options:
  - attic:
      padding_top:                      400
      padding_bottom:                   50
      opacity:                          0.5
      slides:
        - url:                          /assets/images/pages/kickstarter/web_in_a_day/200_first_awesome_web/000-joanna-kosinska-1920x1280.jpg
          alt:                          Photo by Joanna Kosinska on Unsplash
          alignY:                       top
          badge:
            type:                       unsplash
            author:                     Joanna Kosinska
            href:                       https://unsplash.com/@joannakosinska
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set page (local) attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>

// enable UI macros, e.g kbd:[], for Asciidoctor
// See: https://docs.asciidoctor.org/asciidoc/latest/macros/keyboard-macro/
:experimental:

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="all" %}


// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Include sub-documents
// -----------------------------------------------------------------------------
include::{documentdir}/200_first_awesome_web.asciidoc[]

== Questions

include::{includedir}/parts.asciidoc[tag=questions-chapter]

[role="big bold"]
mdi:head-question-outline[24px, md-grey-700 mb-5 mr-2]
link:{j1-kickstart-wiad--answer-7}[Question 7, {browser-window--new}]

[QUESTION]
====
The J1 Template System is using _NodeJS_. For what?
====

[role="big bold"]
mdi:head-question-outline[24px, md-grey-700 mb-5 mr-2]
link:{j1-kickstart-wiad--answer-8}[Question 8, {browser-window--new}]

[QUESTION]
====
A code editor is a critical tool to manage J1 projects. What are the
main reasons?
====

[role="big bold"]
mdi:head-question-outline[24px, md-grey-700 mb-5 mr-2]
link:{j1-kickstart-wiad--answer-9}[Question 9, {browser-window--new}]

[QUESTION]
====
The Jekyll builder engine make use of a central configuration file.
Give two examples of the settings and what do they control.
====

[role="big bold"]
mdi:head-question-outline[24px, md-grey-700 mb-5 mr-2]
link:{j1-kickstart-wiad--answer-10}[Question 10, {browser-window--new}]

[QUESTION]
====
J1 is using two environment modes to control the HTML outputs for a website.
What modes are available and what do they control?
====

== Summarize!

include::{includedir}/parts.asciidoc[tag=summarize]

=== Recap

include::{includedir}/parts.asciidoc[tag=recap_200_first_awesome_web]

=== Whats Next

include::{includedir}/parts.asciidoc[tag=whats_next_200_first_awesome_web]


=== All Chapters

include::{includedir}/parts.asciidoc[tag=chapters]
include::{includedir}/parts.asciidoc[tag=chapters_200_first_awesome_web]

=== Further Reading

include::{includedir}/parts.asciidoc[tag=further_reading]
include::{includedir}/parts.asciidoc[tag=further_200_first_awesome_web]

== Leave a comment
